// Generates src/schemas.ts from ../kirk/schemas/*.schema.json (the Python package owns the schemas).
// Usage: node scripts/gen-schemas.mjs [--check]   (--check exits 1 if src/schemas.ts is out of date)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const names = [
  ["librarySchema", "library"],
  ["commandSchema", "command"],
  ["snapshotSchema", "snapshot"],
];

export function render() {
  let out =
    "// Generated by scripts/gen-schemas.mjs from kirk/schemas/*.schema.json. Do not edit; run `npm run gen:schemas`.\n\n";
  for (const [ident, name] of names) {
    const schema = JSON.parse(readFileSync(new URL(`../kirk/schemas/${name}.schema.json`, root), "utf-8"));
    out += `export const ${ident}: any = ${JSON.stringify(schema, null, 2)};\n\n`;
  }
  return out.replace(/\n\n$/, "\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = new URL("src/schemas.ts", root);
  const text = render();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf-8") !== text) {
      console.error("src/schemas.ts is out of date: run `npm run gen:schemas`");
      process.exit(1);
    }
  } else {
    writeFileSync(target, text);
  }
}
